name: Build-and-test
on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    uses: ./.github/workflows/test.yml
    permissions:
      actions: write
      contents: read
